#exercicios com fatiamento

frase = input('Digite algo: ')
print(frase[0:5])
print(frase.upper())
print(frase.lower())
print(frase[5])
print(frase[5:])
print(frase.capitalize())
print(frase[3::2])
print(frase.count('o', 0, 12))
print(frase.replace('Python', 'Android'))
print(frase.strip())
print(frase.split()[3])
print(len(frase.strip()))
print(frase.lower().find('android'))
